import { readFileSync } from "node:fs";
import { expect, it } from "vitest";
import { runParity } from "../../packages/compatibility-oracle/src/index.js";
import type { CompatibilityScenario, ParityProvider, ReferenceProvider } from "../../packages/compatibility-oracle/src/index.js";
import { baseline, sha } from "../support/harness.js";
const scenario = JSON.parse(readFileSync(new URL("../fixtures/parity/properties/typed-number.scenario.json", import.meta.url), "utf8")) as CompatibilityScenario;
const snapshot = { graphLabel: scenario.id, nodes: [{ uuid: "00000000-0000-4000-8000-000000000461", kind: "property", content: "rating", tags: [], refs: [], properties: { value: 5 } }] };
const candidate: ParityProvider = { name: "phase04-properties-candidate", async execute() { return snapshot; } };
const reference: ReferenceProvider = { name: "phase04-fixture-test-double", baselineCommit: sha, evidence: "test-double", async execute() { return snapshot; } };
it("keeps Phase 04 provenance explicit", async () => { await expect(runParity(baseline, scenario, candidate, reference)).resolves.toMatchObject({ equal: true, compatible: false }); });
