import { readFileSync } from "node:fs";
import { expect, it } from "vitest";
import { runParity } from "../../packages/compatibility-oracle/src/index.js";
import type { CompatibilityScenario, ParityProvider, ReferenceProvider } from "../../packages/compatibility-oracle/src/index.js";
import { createQueryEngine } from "../../packages/query-engine/src/index.js";
import { baseline, sha } from "../support/harness.js";
const scenario = JSON.parse(readFileSync(new URL("../fixtures/parity/query/task-status.scenario.json", import.meta.url), "utf8")) as CompatibilityScenario;
const snapshot = { graphLabel: scenario.id, nodes: [{ uuid: "00000000-0000-4000-8000-000000000501", kind: "query-result", content: "task", tags: [], refs: [], properties: { rows: ["task"] } }] };
const candidate: ParityProvider = { name: "phase05-query-candidate", async execute() { const rows = await createQueryEngine({ facts: [{ entity: "task", attribute: ":task/status", value: "TODO" }] }).simple<string[]>("(task TODO)"); return { ...snapshot, nodes: [{ ...snapshot.nodes[0]!, properties: { rows } }] }; } };
const reference: ReferenceProvider = { name: "phase05-fixture-test-double", baselineCommit: sha, evidence: "test-double", async execute() { return snapshot; } };
it("keeps Phase 05 query provenance explicit", async () => { await expect(runParity(baseline, scenario, candidate, reference)).resolves.toMatchObject({ equal: true, compatible: false }); });
